### ISSUE TITLE
comprehension of test_invalid_json

### ISSUE THREAD

**Issue by as142** [qutebrowser/experiments#7]
Hi there, When I was learning and trying to understand the function "test_invalid_json" in experiments/tests/unit/misc/test_autoupdate.py, I was confused about the description of its delivered function. My understanding of this code snippet is "test on_client_success() with invalid json". Do I understand that right?

**Comment by The-Compiler** [comment]
I'm a bit confused by the question - can you elaborate? Yeah, that test checks whether `PyPIVersionClient` acts correctly if it gets invalid JSON back from the server.
